current_exercise = "array_basics"
last_updated = 2026-09-18T22:39:46.643768006+05:30

[completed_exercises]
  break_continue = true
  closures = true
  comments = true
  constants = true
  defer_statements = true
  for_loops = true
  formatting = true
  function_definition = true
  function_types = true
  go_types = true
  goto_labels = true
  hello = true
  if_statements = true
  imports = true
  main_function = true
  multiple_declaration = true
  multiple_imports = true
  named_returns = true
  package = true
  panic_recover = true
  parameters = true
  print_functions = true
  program_structure = true
  range_loops = true
  recursive_functions = true
  return_values = true
  select_statements = true
  semicolons = true
  short_declaration = true
  switch_statements = true
  type_conversion = true
  type_inference = true
  type_switches = true
  var_declaration = true
  variable_scope = true
  variadic_functions = true
  zero_values = true
